Add method to check if repo vulnerability alerts are enabled
octokit/octokit.net pull request #2453
Opened 2022-05-26 21:52 UTC by lboynton

Just reopening #2334, is anyone able to review what would need to be done integration test wise to get this merged?

2022-07-01 20:05 UTC, nickfloyd requested changes
Hey @lboynton thank you for your effort here and a huge apology for the delay in getting some 👀 on it.  I made a few comments about no longer needing the preview header for the API call (the preview was promoted in 09/2021) - so you can remove those and use the default if you'd like.

✅ As far as integration tests - I think you might be ok there - you've got coverage for the client there as well as unit tests... thanks for doing those! 

❇️ You could add the positive (204) and negative (404) tests for the GET endpoint
❇️ If you wanted to/ or had time you could add the other CRUP ops (PUT and DELETE)

❌  Also, there seems to be a merge conflict, but that should go away once you remove the preview changes.

Thanks again!  Looking forward to getting this in.

2022-07-03 10:55 UTC, lboy2 commented on Octokit/Helpers/AcceptHeaders.cs
> +        public const string DependencyAlertsPreview = "application/vnd.github.dorian-preview+json";
Removed

2022-07-03 10:56 UTC, lboynton commented on Octokit/Helpers/AcceptHeaders.cs
> +        public const string DependencyAlertsPreview = "application/vnd.github.dorian-preview+json";
Removed

2022-07-03 10:56 UTC, lboynton commented on Octokit/Clients/RepositoriesClient.cs
> +        [Preview("dorian")]
Removed

2022-07-03 10:56 UTC, lboynton commented on Octokit.Tests/Clients/RepositoriesClientTests.cs
> +                    null, AcceptHeaders.DependencyAlertsPreview).Returns(responseTask);
Removed

2022-07-03 10:56 UTC, lboynton commented on Octokit/Clients/RepositoriesClient.cs
> +                var response = await Connection.Get<object>(ApiUrls.RepositoryVulnerabilityAlerts(owner, name), null, AcceptHeaders.DependencyAlertsPreview).ConfigureAwait(false);
Removed

2022-07-03 11:01 UTC, lboynton commented
Thanks for reviewing @nickfloyd! I've merged in the upstream changes in `main` to resolve the conflicts.

>You could add the positive (204) and negative (404) tests for the GET endpoint

I believe these are already there in the `TheAreVulnerabilityAlertsEnabledMethod` class?

>If you wanted to/ or had time you could add the other CRUP ops (PUT and DELETE)

I might leave that to a separate PR for me or someone else :)

2022-07-06 16:29 UTC, nickfloyd approved these changes
This looks good!  Thank you again for the contributions here! ✅

2022-07-06 16:29 UTC, merged

2022-07-06 16:53 UTC, lboynton commented
Thanks! :)

2022-07-13 20:22 UTC, nickfloyd commented
release_notes: Add method to check if repo vulnerability alerts are enabled